{"level": "error", "exception": {"values": [{"mechanism": {"type": "django", "handled": false}, "module": null, "type": "Exception", "value": "Exception triggered on purpose to debug error handling", "stacktrace": {"frames": [{"filename": "django/core/handlers/exception.py", "abs_path": "/mnt/datacrypt/dev/bugsink/lib/python3.10/site-packages/django/core/handlers/exception.py", "function": "inner", "module": "django.core.handlers.exception", "lineno": 55, "pre_context": ["    else:", "", "        @wraps(get_response)", "        def inner(request):", "            try:"], "context_line": "                response = get_response(request)", "post_context": ["            except Exception as exc:", "                response = response_for_exception(request, exc)", "            return response", "", "        return inner"], "vars": {"request": "<WSGIRequest: GET '/trigger-error/'>", "exc": "Exception('Exception triggered on purpose to debug error handling')", "get_response": "<bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x7f7ad677c400>>"}, "in_app": false}, {"filename": "django/core/handlers/base.py", "abs_path": "/mnt/datacrypt/dev/bugsink/lib/python3.10/site-packages/django/core/handlers/base.py", "function": "_get_response", "module": "django.core.handlers.base", "lineno": 197, "pre_context": ["            wrapped_callback = self.make_view_atomic(callback)", "            # If it is an asynchronous view, run it in a subthread.", "            if iscoroutinefunction(wrapped_callback):", "                wrapped_callback = async_to_sync(wrapped_callback)", "            try:"], "context_line": "                response = wrapped_callback(request, *callback_args, **callback_kwargs)", "post_context": ["            except Exception as e:", "                response = self.process_exception_by_middleware(e, request)", "                if response is None:", "                    raise", ""], "vars": {"self": "<django.core.handlers.wsgi.WSGIHandler object at 0x7f7ad677c400>", "request": "<WSGIRequest: GET '/trigger-error/'>", "response": "None", "callback": "<function trigger_error at 0x7f7ad639a9e0>", "callback_args": [], "callback_kwargs": {}, "middleware_method": "<function CsrfViewMiddleware.process_view at 0x7f7ad51e4ca0>", "wrapped_callback": "<function trigger_error at 0x7f7ad529ae60>"}, "in_app": false}, {"filename": "bugsink/views.py", "abs_path": "/mnt/datacrypt/dev/bugsink/bugsink/views.py", "function": "trigger_error", "module": "bugsink.views", "lineno": 9, "pre_context": ["from django.views.decorators.cache import cache_control", "from django.http import FileResponse, HttpRequest, HttpResponse", "", "", "def trigger_error(request):"], "context_line": "    raise Exception(\"Exception triggered on purpose to debug error handling\")", "post_context": ["", "", "@require_GET", "@cache_control(max_age=60 * 60 * 24, immutable=True, public=True)", "def favicon(request: HttpRequest) -> HttpResponse:"], "vars": {"request": "<WSGIRequest: GET '/trigger-error/'>"}, "in_app": true}]}}]}, "event_id": "417b00a4241e48f382106c9692471aca", "timestamp": "2023-11-13T11:04:07.305033Z", "breadcrumbs": {"values": []}, "transaction": "/trigger-error/", "transaction_info": {"source": "route"}, "contexts": {"trace": {"trace_id": "2e2be3ad91fa47a39e5425c4c7fe88aa", "span_id": "be961615fcea734e", "parent_span_id": "be9144ff6b3515e1", "op": "event.django", "description": "sentry_sdk.integrations.django._got_request_exception"}, "runtime": {"name": "CPython", "version": "3.10.12", "build": "3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]"}}, "extra": {"sys.argv": ["manage.py", "runserver", "127.0.0.1:8000"]}, "modules": {"click": "8.1.7", "certifi": "2023.7.22", "charset-normalizer": "3.3.2", "pip": "22.0.2", "pytz": "2023.3.post1", "sentry-sdk": "1.32.0", "python-dateutil": "2.8.2", "pyyaml": "6.0.1", "sqlparse": "0.4.4", "idna": "3.4", "binaryornot": "0.4.4", "markdown-it-py": "3.0.0", "types-python-dateutil": "2.8.19.14", "markupsafe": "2.1.3", "typing_extensions": "4.8.0", "requests": "2.31.0", "cookiecutter": "2.4.0", "jinja2": "3.1.2", "jsonschema-specifications": "2023.7.1", "rich": "13.6.0", "djangorestframework": "3.14.0", "pygments": "2.16.1", "urllib3": "2.0.7", "arrow": "1.3.0", "jsonschema": "4.19.2", "text-unidecode": "1.3", "python-slugify": "8.0.1", "rpds-py": "0.12.0", "django-tailwind": "3.6.0", "attrs": "23.1.0", "django": "4.2.7", "chardet": "5.2.0", "six": "1.16.0", "setuptools": "59.6.0", "mdurl": "0.1.2", "asgiref": "3.7.2", "referencing": "0.30.2"}, "request": {"url": "http://localhost:8000/trigger-error/", "query_string": "", "method": "GET", "env": {"SERVER_NAME": "localhost", "SERVER_PORT": "8000"}, "headers": {"Content-Length": "", "Content-Type": "text/plain", "Host": "localhost:8000", "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8", "Accept-Language": "en-US,en;q=0.5", "Accept-Encoding": "gzip, deflate, br", "Connection": "keep-alive", "Cookie": "[Filtered]", "Upgrade-Insecure-Requests": "1", "Sec-Fetch-Dest": "document", "Sec-Fetch-Mode": "navigate", "Sec-Fetch-Site": "none", "Sec-Fetch-User": "?1"}}, "release": "18de710a82c49b44770478de76effcf10c49c65b", "environment": "production", "server_name": "pop-os", "sdk": {"name": "sentry.python.django", "version": "1.32.0", "packages": [{"name": "pypi:sentry-sdk", "version": "1.32.0"}], "integrations": ["argv", "atexit", "dedupe", "django", "excepthook", "logging", "modules", "redis", "stdlib", "threading"]}, "platform": "python", "_meta": {"request": {"headers": {"Cookie": {"": {"rem": [["!config", "s"]]}}}}}}